### ISSUE TITLE
Students need to delete database to get tests to pass

### ISSUE THREAD

**Issue by talum** [learn-co-curriculum/activerecord-costume-store-todo#48]
Bunch of students have been running the test suite intermittently, which runs the migrations. Then they modify the migration and are surprised when the tests don't pass. Migrations won't get run again.

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#61.  We will add this to our internal work queue and notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team

**Comment by maxwellbenton** [comment]
Hi @talum,

Thank you for reporting this issue. We've updated the support files and instructions for this lesson so that migrations can be run repeatedly and include messaging on rolling back migrations if necessary, which should prevent this issue from occuring going forward.

Thank you for providing this feedback and contributing to a Learn lesson!
