### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by curiositypaths** [learn-co-curriculum/activerecord-costume-store-todo#61]
PROBLEM: Review lab flow. See issues #60, #48, #42 
NOTIFY: @talum, @wlycdgrfromflatiron

**Comment by JerYoMat** [comment]
Hi,
just spent the better part of an hour with the same problem.  While I can see that this would not rank as a 'must have' or 'high priority' story/feature  within the product backlog, an easy fix may be to add in a short piece of text to the error message.  Currently when a student is unable to run rake db:migrate the message is as follows:
________________________________________________
WARN: Unresolved specs during Gem::Specification.reset:
      minitest (~> 5.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
_________________________________________________
Given that the current text increases workload on the TS, and Learn Advisor teams a minimal resource allocation fix could be the following. 
______________________________________________________________
WARN: Unresolved specs during Gem::Specification.reset:
      minitest (~> 5.1)
WARN: Clearing out unresolved specs.
Try deleting the following files and running 'rake db:migrate' in the terminal once more.  
db/halloween-development.db
db/halloween-test.db 
If this does not resolve the issues please report a bug.

**Comment by Sdcrouse** [comment]
Hello. I would like to make a suggestion regarding Issue #48 

All you need to do to reverse the migrations when "running the test suite intermittently" is to run 'rake db:rollback'.

If the README or the test output includes that piece of information, that would probably clear up a lot of confusion.

**Comment by maxwellbenton** [comment]
Hi @JerYoMat and @Sdcrouse,

Thank you for this feedback. We've updated the support files and instructions for this lesson so that migrations can be run repeatedly without error and include messaging on rolling back migrations after updating, which should prevent this issue from occuring going forward, along with other general bug fixes. We apologize for any frustration you might have encountered during this process. 

Thank you both for contributing to this lesson.
