### ISSUE TITLE
rake db:migrate errors

### ISSUE THREAD

**Issue by JoeQuattrone** [learn-co-curriculum/activerecord-costume-store-todo#66]
I ran a migration on an incorrect migration file and failed some of the tests. Easy fix right? Just add columns to the table and run on another migration. NOPE. Didn't work like that. Got a bunch of DB errors and was advised to restart the lab by learn coach. Frustrating as I lost a good chunk of my work.

**Comment by maxwellbenton** [comment]
Hi @JoeQuattrone,

Thank you for opening this issue and providing feedback. We've updated this lab's support files and instructions so that it no longer produces errors when running migrations multiple times and includes instructions on how to roll back migrations a migration is not changing schema, which should resolve this issue going forward.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

Thank you for contributing to a Learn lesson. 💙
