### ISSUE TITLE
Issue with tests failing then passing

### ISSUE THREAD

**Issue by eponsonby** [learn-co-curriculum/activerecord-costume-store-todo#68]
I noticed while doing this lab that when I would run the test, some of the tests would fail (specifically around which attributes existed) and then I would wait a second, run the test again and the same test would pass.

**Comment by maxwellbenton** [comment]
Hi @eponsonby,

Thank you for opening this issue and providing feedback. This was due to a bug in the support files that has now been corrected with other updates to the instructions and support files for this lesson. We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
